### ISSUE TITLE
Does not work with react-i18next version 16.0.0

### ISSUE THREAD

**Issue by tahvane1** [sergiodxa/remix-i18next#356]
### Describe the bug

Error message on startup 

react-i18next:: useTranslation: You will need to pass in an i18next instance by using ini
tReactI18next {
  code: "NO_I18NEXT_INSTANCE",
}

and due to that error i18n.changeLanguage is not a function

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

update project dependencies  react-i18next version16.0.0

### Expected behavior

Should work

### Platform

Ubuntu
